version: "3.9"
services:
    mysql:
        image: ${MYSQL_CONTAINER_NAME}:${MYSQL_VERSION}
        container_name: ${MYSQL_CONTAINER_NAME}
        volumes: 
            - ./db/${MYSQL_CONTAINER_NAME}/data:/var/lib/mysql
            - ./db/${MYSQL_CONTAINER_NAME}/conf.d:/etc/mysql/conf.d
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: password
            MYSQL_DATABASE: docker
            MYSQL_USER: docker-user
            MYSQL_PASSWORD: docker-pass
            TZ: 'Asia/Tokyo'
        command: --default-authentication-plugin=mysql_native_password
        ports:
            - ${MYSQL_PORT}:3306

    # nginx:
    #     image: nginx:${NGINX_VERSION}
    #     container_name: nginx
    #     ports:
    #         - ${NGINX_PORT}:8000
    #     volumes: 
    #         - ./web/nginx/conf:/etc/nginx/conf.d
    #         - ./web/nginx/uwsgi_params:/etc/nginx/uwsgi_params
    #         - ./static:/static
    #     depends_on: 
    #         - django
    
    laravel:
        build:
            context: ./${LARAVEL_CONTAINER_NAME}/
            args:
                - LARAVEL_VERSION=${LARAVEL_VERSION}
                - PHP_IMAGE_VERSION=${PHP_IMAGE_VERSION}
                - COMPOSER_VERSION=${COMPOSER_VERSION}
                - LARAVEL_APP_GIT_BRANCH=${LARAVEL_APP_GIT_BRANCH}
                - LARAVEL_APP_GIT_REPOS=${LARAVEL_APP_GIT_REPOS}
        container_name: ${LARAVEL_CONTAINER_NAME}
        # command: 
        # entrypoint: 
        tty: true
        volumes: 
            - ./${LARAVEL_CONTAINER_NAME}/work:/work
        ports: 
            - ${LARAVEL_PORT}:8000
        depends_on: 
            - ${MYSQL_CONTAINER_NAME}
    django:
        build:
            context: ./${DJANGO_CONTAINER_NAME}/
            args:
                - DJANGO_VERSION=${DJANGO_VERSION}
                - PYTHON_IMAGE_VERSION=${PYTHON_IMAGE_VERSION}
                - DJANGO_GIT_BRANCH=${DJANGO_APP_GIT_BRANCH}
                - DJANGO_GIT_REPOS=${DJANGO_APP_GIT_REPOS}
        container_name: ${DJANGO_CONTAINER_NAME}
        # command: uwsgi --socket :${DJANGO_PORT} --module project.wsgi
        entrypoint: "/work/entrypoint.sh"
        tty: true
        volumes: 
            - ./${DJANGO_CONTAINER_NAME}/work:/work
        ports: 
            - ${DJANGO_PORT}:8000
        expose: 
            - ${DJANGO_PORT}
        depends_on: 
            - ${MYSQL_CONTAINER_NAME}
